@startuml
title Context View
scale 2

package "Connect 4 Game" {
    usecase Game
    usecase Board
    usecase Graphics
    usecase Turns

    [Game] ..> [Board]
    [Game] ..> [Graphics]
    [Game] ..> [Turns]

    [Graphics] ..> [Board]
}

actor Player
component pygame

[Game] <-- Player : interacts with
[Graphics] --> pygame : uses

@enduml
