@startuml
scale 2
title "Design Analysis"
class Logical_View {
    +Piece : class
    +Spot : class
    +Board : class
    +Game : class
}

class Process_View {
    +Start Game?
    +StartGame()
    +SwitchPlayer()
    +PlayTurn()
    +Victory?
    +Play Again?
    +Quit()
}

class Development_View {
    +typing : package
    +Board Module : module
    +Main Module : module
}

class Physical_View {
}

Context_View <-- Logical_View
Context_View <-- Process_View
Context_View <-- Development_View
Context_View <-- Physical_View

@enduml
