@startuml
title Development View
scale 2

package "Connect 4 Game" {
  [Game Module]
  [Board Module]
  [Turns Module]
  [Graphics Module]
}

[Game Module] ..> [Board Module] : uses
[Game Module] ..> [Turns Module] : uses
[Game Module] ..> [Graphics Module] : uses

[Graphics Module] ..> [Board Module] : uses
[Graphics Module] ..> [pygame] : uses

@enduml
