@startuml
scale 2
title "Development View"

package "typing" {
    [Optional]
}

frame "Board Module" {
    [Board Module] --> [typing] : uses
    [Spot] --> [FullError] : uses
    [Spot] --> [Piece] : uses
    [Board] --> [Spot] : uses
    [Game] --> [Board] : uses
}

frame "Main Module" {
    [Main Module] --> [Board Module] : uses
}

@enduml
