@startuml
title Logical View
scale 2

class Game {
  +game_loop(): None
  +drop_piece(): None
  +has_won(): boolean
  +switch_player(): None
}

class Board {
  +rows: int
  +cols: int
  +spot: tuple[int, int]
}

class Spot {
  +occupant: int
  +isEmpty(): boolean
}

Game -- Board
Board -- Spot

@enduml
