@startuml
title Physical View
scale 2

node "Computer" {
    artifact "Connect 4 Game.exe" {
        component "Python Interpreter" {
            component "Pygame Library"
        }
        component "Application" {
            skinparam ComponentBackgroundColor Aqua
            component "Game" {
                note right: Handles the game loop
            }
            component "Board" {
                note right: Manages the state of the game board
            }
            component "Interface" {
                note right: Manages user interactions
            }
            component "Graphics" {
                note right: Represents the game in graphical form
            }
        }
    }
}

skinparam componentStyle uml2
skinparam rectangle {
    BackgroundColor PaleGreen
    BorderColor Black
    Shadowing true
}
skinparam node {
    BackgroundColor Grey
    BorderColor Black
    Shadowing true
}
skinparam artifact {
    BackgroundColor CornflowerBlue
    BorderColor Black
    Shadowing true
}
@enduml
