@startuml
scale 2
title "Process View"
start

:Start Game;

repeat
  repeat
    :Switch Player;
    :Play Turn;
  repeat while (Victory?) is (no)
  ->yes;
repeat while (Play Again?) is (yes)
->no;

stop
@enduml
