@startuml
scale 2
title "Board Class Diagram"
class Board {
    -_board : list[list[Spot]]

    +__init__(cols: int, rows: int) : None
    -_rows : int
    -_cols : int
    -_spot : Spot

    +spot() : Spot
    +rows() : int
    +cols() : int
    +reset() : None
    +get_player_at_spot(x: int, y: int) : int
    +width() : int
    +height() : int
    +drop_piece(x: int, player_number: int) : None
    +is_player(x: int, y: int, player_number: int) : bool
    +_diagonal_win(player_number: int) : bool
    +has_won(player_number: int) : bool
}
@enduml