@startuml
scale 2
title "Game Class Diagram"
class Game {
    +__init__() : None
    -_turn : Turns
    -_board : Board
    -_screen : Screen
    -_color : Color
    -_draw : Draw
    -_draw2 : Draw

    +turn() : Turns
    +board() : Board
    +screen() : Screen
    +color() : Color
    +draw() : Draw
    +_print_winner_message(player: int) : None
    +_print_tie_message() : None
    +_print_replay_message() : None
    +_replay(event: pygame.event.EventType) : bool
    +handle_mouse_motion(screen: pygame.Surface, event_pos: list[int]) : None
    +handle_mouse_click(event_pos: list[float]) : Optional[int]
    +game_loop() : None
}
@enduml